
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  azureSubscription: '<Your-Azure-Service-Connection-Name>'

steps:
- task: UseTerraform@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(terraformVersion)

- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'

- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    environmentServiceName: $(azureSubscription)

- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    additionalArgs: '-auto-approve'
    environmentServiceName: $(azureSubscription)

- task: AzureCLI@2
  displayName: 'Manual Monitoring Check'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az monitor metrics list --resource /subscriptions/<subscription-id>/resourceGroups/monitoring-rg --metric "Percentage CPU"
