# Trigger the pipeline whenever changes are pushed to the 'main' branch
name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

# No 'permissions:' block needed for old-style SP + secret
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: '1.6.0'  # Or whichever version you want
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # --------------------------------------
      # Azure CLI Login using the JSON 'creds'
      # --------------------------------------
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # optionally, you can add:
        # allow-no-subscriptions: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Manual Monitoring Check
        run: |
          az monitor metrics list \
            --resource /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/monitoring-rg \
            --metric "Percentage CPU" \
            --output table

      - name: Terraform Destroy (Manual Cleanup)
        if: github.ref == 'refs/heads/main' && success()
        run: terraform destroy -auto-approve
