# Trigger the pipeline whenever changes are pushed to the 'main' branch
name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

# We do NOT need id-token permissions for a classic SP + secret approach.
# So no 'permissions:' block is required here.

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VERSION: '1.6.0' # Or whichever Terraform version you need

    steps:
      - name: Pre Azure CLI Login
        run: echo "About to authenticate with Azure using SP + Client Secret."

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # -- Azure CLI Login with Service Principal + Client Secret --
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          auth-type: spn
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Manual Monitoring Check
        run: |
          az monitor metrics list \
            --resource /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/monitoring-rg \
            --metric "Percentage CPU" \
            --output table

      - name: Terraform Destroy (Manual Cleanup)
        if: github.ref == 'refs/heads/main' && success()
        run: terraform destroy -auto-approve
